### ISSUE TITLE
Join on Model Instead of Data Source for batchQuery

### ISSUE THREAD

**Issue by tmichaeldb** [mindsdb/mindsdb-js-sdk#32]
The current [documentation](https://docs.mindsdb.com/sql/api/select#bulk-predictions-2) advises users to join against a model when performing bulk predictions (batch queries). However, [BatchQueryOptions](https://mindsdb.github.io/mindsdb-js-sdk/interfaces/models_queryOptions.BatchQueryOptions.html) uses join to join against the data source instead. This is unintuitive for users and should be the other way around.

**Comment by danshapir** [comment]
#33
