### ISSUE TITLE
[Hacktoberfest] A function to remove a project

### ISSUE THREAD

**Issue by martyna-mindsdb** [mindsdb/mindsdb-js-sdk#51]
## Task

Implement a function to remove a project in JavaScript SDK.

Follow similar pattern as in the [Python SDK](https://github.com/mindsdb/minds_python_sdk).

## Deliverables

Create a PR to this repository with the implementation.

## :loudspeaker: Additional rewards :trophy:

This issue brings up to :five:  :zero:  points for SWAG and entry into the draw for a  :point_down: :
-  :three:  :x:   :computer:  [Razer Blade 16 Gaming Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0510TEN3-R3U1)
- :shirt: :bear:  [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)

:information_source: For more info check out https://mindsdb.com/hacktoberfest :point_left:

**Comment by md-abid-hussain** [comment]
@quest-bot embark

**Comment by kom-senapati** [comment]
@quest-bot embark

**Comment by kom-senapati** [comment]
Its unclear how to remove it, need more info

Python method for this:
https://github.com/mindsdb/mindsdb_python_sdk/blob/main/mindsdb_sdk/projects.py
![image](https://github.com/user-attachments/assets/23959ed7-3244-4157-a990-338bcd7040b5)

Rest API:
No docs
https://docs.mindsdb.com/rest/projects/drop

**Comment by martyna-mindsdb** [comment]
@ea-rus @ZoranPandovski ^^

**Comment by md-abid-hussain** [comment]
I am working on it i know how to implement it. I will complete it by today.

**Comment by kom-senapati** [comment]
> I am working on it i know how to implement it. I will complete it by today.

Tell me as well bro

**Comment by md-abid-hussain** [comment]
#76 need to be merged before this can be implemented, otherwise it will cause merge conflict.
