### ISSUE TITLE
[Hacktoberfest] A function to remove a model

### ISSUE THREAD

**Issue by martyna-mindsdb** [mindsdb/mindsdb-js-sdk#52]
## Task

Implement a function to remove a model in JavaScript SDK.

Follow similar pattern as in the [Python SDK](https://github.com/mindsdb/minds_python_sdk).

## Deliverables

Create a PR to this repository with the implementation.

## :loudspeaker: Additional rewards :trophy:

This issue brings up to :five:  :zero:  points for SWAG and entry into the draw for a  :point_down: :
-  :three:  :x:   :computer:  [Razer Blade 16 Gaming Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0510TEN3-R3U1)
- :shirt: :bear:  [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)

:information_source: For more info check out https://mindsdb.com/hacktoberfest :point_left:

**Comment by kom-senapati** [comment]
@quest-bot embark
