### ISSUE TITLE
[Hacktoberfest] Change the name of `adjust` function to `finetune`

### ISSUE THREAD

**Issue by martyna-mindsdb** [mindsdb/mindsdb-js-sdk#54]
## Task

Change the name of the `adjust` function to `finetune` in JavaScript SDK.

Follow similar pattern as in the [Python SDK](https://github.com/mindsdb/minds_python_sdk).

## Deliverables

Create a PR to this repository with the implementation.

## :loudspeaker: Additional rewards :trophy:

This issue brings up to :three:  :zero:  points for SWAG and entry into the draw for a  :point_down: :
-  :three:  :x:   :computer:  [Razer Blade 16 Gaming Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0510TEN3-R3U1)
- :shirt: :bear:  [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)

:information_source: For more info check out https://mindsdb.com/hacktoberfest :point_left:

**Comment by Aazma11** [comment]
I am Working on this issue
@martyna-mindsdb 
Please assign this to me.

**Comment by kom-senapati** [comment]
finetune already present in src/models/model.ts
![image](https://github.com/user-attachments/assets/fc8c4dd3-112a-42bb-bfe9-de7289723b65)

**Comment by kom-senapati** [comment]
I couldn't find the adjust function in `src/models/model.ts`.Is it somewhere else?

**Comment by martyna-mindsdb** [comment]
@kom-senapati 
You're right. This has been updated already. Thanks.
