### ISSUE TITLE
Add Event Name to Second Image for Consistency

### ISSUE THREAD

**Issue by Aazma11** [mindsdb/mindsdb-js-sdk#59]
I noticed that the first picture shows both the event name and date, while the second picture only shows the date. To make it clearer, I suggest adding the event name to the second picture. This will help users understand the information better and keep things consistent.
Can you assign this issue to me under hacktoberfest.

![mindsdb](https://github.com/user-attachments/assets/c47f5118-29ca-4a5a-9040-cc6ae564ed84)

**Comment by chandrevdw31** [comment]
@Aazma11 please note that the website is not open source and therefore not part of hacktoberfest. Also the first is an actual in person event while the other was a youtube stream so this issue is not valid
