### ISSUE TITLE
"403 Forbidden Error When Publishing mindsdb-js-sdk to npm"

### ISSUE THREAD

**Issue by naaa760** [mindsdb/mindsdb-js-sdk#77]
### Description

Encountering a 403 Forbidden error when attempting to publish the mindsdb-js-sdk package to npm.
Steps to Reproduce

    Run npm publish
    Receive the error: 403 Forbidden - You do not have permission to publish this package.

### Expected Behavior

Package should be published successfully.

### Actual Behavior

Publishing fails with a 403 Forbidden error.

### Possible Causes

    Insufficient permissions or npm account issues.

### Suggested Solutions

    Verify npm authentication and package permissions.

![Screenshot from 2024-10-19 09-27-59](https://github.com/user-attachments/assets/35d189cb-8b6f-46d2-a313-4145d46b02a9)

**Comment by ZoranPandovski** [comment]
@naaa760 You can't publish this to npm since you don't have access, that can be done only by mindsdb team
