### ISSUE TITLE
[Hacktoberfest] A set of functions for Skills (that are assigned to AI Agents)

### ISSUE THREAD

**Issue by martyna-mindsdb** [mindsdb/mindsdb-js-sdk#93]
## Task

Implement a set of functions for Skills (that are assigned to AI Agents) in JavaScript SDK.

Follow similar pattern as in the [Python SDK](https://github.com/mindsdb/minds_python_sdk).

[Here are the Python SDK docs that cover Skills functions](https://docs.mindsdb.com/sdks/python/agents_skills).

## Deliverables

Create a PR to this repository with the implementation.

## :loudspeaker: Additional rewards :trophy:

This issue brings up to :five:  :zero:  points for SWAG and entry into the draw for a  :point_down: :
-  :three:  :x:   :computer:  [Razer Blade 16 Gaming Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0510TEN3-R3U1)
- :shirt: :bear:  [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)

:information_source: For more info check out https://mindsdb.com/hacktoberfest :point_left:

**Comment by md-abid-hussain** [comment]
i want to work on this

**Comment by chandrevdw31** [comment]
@md-abid-hussain are you making progress on this?

**Comment by md-abid-hussain** [comment]
Yes i have implemented most of the methods
