### ISSUE TITLE
[Hacktoberfest] A set of functions for Knowledge Bases (that are assigned to AI Agents as Skills)

### ISSUE THREAD

**Issue by martyna-mindsdb** [mindsdb/mindsdb-js-sdk#94]
## Task

Implement a set of functions for Knowledge Bases (that are assigned to AI Agents as Skills) in JavaScript SDK.

Follow similar pattern as in the [Python SDK](https://github.com/mindsdb/minds_python_sdk).

[Here are the Python SDK docs that cover Knowledge Bases functions](https://docs.mindsdb.com/sdks/python/agents_knowledge_bases).

## Deliverables

Create a PR to this repository with the implementation.

## :loudspeaker: Additional rewards :trophy:

This issue brings up to :five:  :zero:  points for SWAG and entry into the draw for a  :point_down: :
-  :three:  :x:   :computer:  [Razer Blade 16 Gaming Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0510TEN3-R3U1)
- :shirt: :bear:  [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)

:information_source: For more info check out https://mindsdb.com/hacktoberfest :point_left:

**Comment by adityaraj31** [comment]
Hey I want to work on this issue, can you provide me some more details about the feature that you need

**Comment by martyna-mindsdb** [comment]
Please see [this doc page](https://docs.mindsdb.com/sdks/python/agents_knowledge_bases#syntax) for all functions related to KBs that are available in Python SDK, and the task is to implement them in JS SDK.

**Comment by md-abid-hussain** [comment]
I want to work on this.
